### ISSUE TITLE
请问undefined reference to 怎么解决

### ISSUE THREAD

**Issue by weibaitu** [ikantech/gm#4]
/usr/bin/ld: /tmp/gm_test-0a45e1.o: in function `test_bn':
gm_test.c:(.text+0x46): undefined reference to `gm_bn_from_hex'
/usr/bin/ld: gm_test.c:(.text+0x70): undefined reference to `gm_bn_from_hex'
/usr/bin/ld: gm_test.c:(.text+0xb1): undefined reference to `GM_BN_P'
/usr/bin/ld: gm_test.c:(.text+0xc7): undefined reference to `GM_BN_N'
/usr/bin/ld: gm_test.c:(.text+0x103): undefined reference to `gm_bn_to_mont'
/usr/bin/ld: gm_test.c:(.text+0x139): undefined reference to `gm_bn_from_mont'
/usr/bin/ld: gm_test.c:(.text+0x28a): undefined reference to `gm_bn_add'
/usr/bin/ld: gm_test.c:(.text+0x301): undefined reference to `gm_bn_sub'
/usr/bin/ld: gm_test.c:(.text+0x345): undefined reference to `gm_bn_to_mont'
/usr/bin/ld: gm_test.c:(.text+0x35f): undefined reference to `gm_bn_to_mont'
/usr/bin/ld: gm_test.c:(.text+0x394): undefined reference to `gm_bn_mont_mul'
/usr/bin/ld: gm_test.c:(.text+0x3bc): undefined reference to `gm_bn_from_mont'

**Comment by ikantech** [comment]
你的编译环境是什么，这种一般是编译环境问题，非代码问题。
